apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
        - name: springboot-hello
          image: springboot-hello-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080